ALTER TABLE "User" ALTER COLUMN "subscriptionStatus" SET DEFAULT 'TRIALING';
ALTER TABLE "Workspace" ALTER COLUMN "planStatus" SET DEFAULT 'TRIALING';
ALTER TABLE "BillingSubscription" ALTER COLUMN "status" SET DEFAULT 'TRIALING';
