ALTER TYPE "AccountSubscriptionStatus" ADD VALUE IF NOT EXISTS 'TRIALING';
ALTER TYPE "AccountSubscriptionStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "AccountSubscriptionStatus" ADD VALUE IF NOT EXISTS 'BLOCKED';
ALTER TYPE "AccountSubscriptionStatus" ADD VALUE IF NOT EXISTS 'MANUAL_UNLOCKED';
ALTER TYPE "BillingInvoiceStatus" ADD VALUE IF NOT EXISTS 'OVERDUE';
ALTER TYPE "BillingInvoiceStatus" ADD VALUE IF NOT EXISTS 'REFUNDED';
